### ISSUE TITLE
enc_dec.py  def generate(sent):

### ISSUE THREAD

**Issue by ustcdane** [neubig/nn4nlp2017-code#14]
There are some error in function  generate(sent)

**Comment by neubig** [comment]
Could you be more specific?

**Comment by stefan-it** [comment]
In `08-condlm/enc_dec.py` for the `generate(sent)` I can reproduce the following error message:

```bash
Traceback (most recent call last):
  File "enc_dec.py", line 177, in <module>
    translated_sent = generate(sent[0])
  File "enc_dec.py", line 114, in generate
    sent_reps = [LSTM_SRC.transduce([LOOKUP_SRC[x] for x in src])[-1] for src in sents]
NameError: name 'sents' is not defined
```

**Comment by ustcdane** [comment]
In https://github.com/neubig/nn4nlp2017-code/blob/master/08-condlm/enc_dec.py , line 114: "sent_reps = [LSTM_SRC.transduce([LOOKUP_SRC[x] for x in src])[-1] for src in sents] " should be "sent_reps = [LSTM_SRC.transduce([LOOKUP_SRC[x] for x in src])[-1] for src in sent]" , line 139 " output_embedding = hidden_state.output()" should be " output_embedding = current_state.output()" ?
